-- ============================================================
-- Seed data generated from src/lib/profile-data.ts (canonical)
-- Run AFTER schema.sql. Idempotent via ON CONFLICT.
-- ============================================================

-- Profile (single row)
INSERT INTO public.profile (id, name, title, tagline, location, email, alt_email, phone, linkedin, linkedin_url, github, github_url, summary, profile_image, whatsapp_number, sort_order) VALUES
(gen_random_uuid(), 'MD. MASUDUL HASAN', 'Software Engineer | FinTech Enthusiast', 'Software Engineer', 'Sunamganj, Sylhet, Bangladesh', '23240442@sstu.ac.bd', 'masudul.2002@gmail.com', '+880 1572 902196', 'linkedin.com/in/masudul2002', 'https://www.linkedin.com/in/masudul2002', 'github.com/masudul2002', 'https://github.com/masudul2002', 'An ambitious dreamer and well-rounded leader seeking knowledge across disciplines. Passionate about building secure, scalable financial technology solutions.', '/images/MASUDUL-HASAN.png', '8801572902196', 0)
ON CONFLICT DO NOTHING;

INSERT INTO public.skills (id, name, icon, icon_color, sort_order) VALUES
(gen_random_uuid(), 'C++', 'fab fa-cuttlefish', 'text-blue-500', 0),
(gen_random_uuid(), 'Python', 'fab fa-python', 'text-yellow-300', 1),
(gen_random_uuid(), 'JavaScript', 'fab fa-js', 'text-yellow-400', 2),
(gen_random_uuid(), 'SQL', 'fas fa-database', 'text-cyan-500', 3),
(gen_random_uuid(), 'HTML5 & CSS3', 'fab fa-html5', 'text-orange-500', 4),
(gen_random_uuid(), 'Git', 'fab fa-git-alt', 'text-red-500', 5),
(gen_random_uuid(), 'Firebase', 'fas fa-fire', 'text-orange-400', 6),
(gen_random_uuid(), 'Linux', 'fab fa-linux', 'text-white', 7)
ON CONFLICT DO NOTHING;

INSERT INTO public.education (id, institution, degree, period, gpa, sort_order) VALUES
(gen_random_uuid(), 'Sunamganj Science and Technology University (SSTU)', 'Bachelor of Science in Computer Science & Engineering (CSE)', 'Nov 2024 – Nov 2028', 'CGPA: 2.94 / 4.00 (1st Semester)', 0),
(gen_random_uuid(), 'Shahid Buddhijibi Govt. College, Rajshahi', 'Higher Secondary Certificate (HSC) — Science', 'Mar 2022 – Nov 2023', 'GPA: 4.58 / 5.00 | Rajshahi Board', 1),
(gen_random_uuid(), 'Al Helal Islami Academy & College, Naogaon', 'Secondary School Certificate (SSC) — Science', 'Jan 2016 – Nov 2021', 'GPA: 5.00 / 5.00 (Golden A+) | Rajshahi Board', 2)
ON CONFLICT DO NOTHING;

INSERT INTO public.org_roles (id, role, sort_order) VALUES
(gen_random_uuid(), 'Treasurer, Computer Club, SSTU (Present)', 0),
(gen_random_uuid(), 'Member of Debating Club, SSTU', 1),
(gen_random_uuid(), 'District Coordinator & Executive Member, International Leadership Competition', 2),
(gen_random_uuid(), 'Director of IT, Anto Huzrapur Jubo Shangho', 3)
ON CONFLICT DO NOTHING;

INSERT INTO public.activities (id, activity, sort_order) VALUES
(gen_random_uuid(), 'Competitive Programming — Codeforces (Target: ICPC 2026)', 0),
(gen_random_uuid(), 'Member, Computer Club & Debating Club — SSTU', 1),
(gen_random_uuid(), 'Open-source web development and personal project portfolio building', 2),
(gen_random_uuid(), 'Regular algorithm practice on LeetCode and Codeforces problem sets', 3)
ON CONFLICT DO NOTHING;

INSERT INTO public.experience (id, key, role, org, period, status, link, brand_color, logo_url, fallback_icon, bullets, cv_bullets, sort_order) VALUES
(gen_random_uuid(), 'treasurer', 'Treasurer', 'Computer Club, Sunamganj Science and Technology University (SSTU)', '2026 – Present (6 mos)', 'Current', '#', 'cyan', '/images/sstucc.png', 'fas fa-wallet', '["Managed financial accounts, membership fees, and budget allocations for all club activities and programming events.","Collaborated with department heads and university administrators to secure sponsorships and funding for annual hackathons and seminars.","Prepared detailed financial reports and balance sheets, ensuring accountability and transparency in all expenditures."]', '["Managing budget allocations, accounts, hackathon funding, and financial reporting."]', 0),
(gen_random_uuid(), 'phitron', 'Phitronista (Campus Ambassador)', 'Phitron', '2025 – Present (1 yr)', 'Current', 'https://phitron.io', 'indigo', '/images/Phitron.png', 'fas fa-graduation-cap', '["Representing Phitron on campus – promoting structured programming education, inspiring peers to join industry-focused courses and driving tech community engagement."]', '["Promoting programming curriculums and coordinating technical engagement sessions."]', 1),
(gen_random_uuid(), 'ph', 'Campus Hero', 'Programming Hero', '2026 – Present (6 mos)', 'Current', 'https://web.programming-hero.com', 'red', '/images/Programming_Hero.jpeg', 'fas fa-code', '["Representing Programming Hero on campus, promoting coding education and structured learning paths.","Organizing peer learning sessions, coding bootcamp awareness, and student onboarding events."]', '["Organized programming study circles and coding bootcamp enrollment campaigns."]', 2),
(gen_random_uuid(), 'yun', 'Campus Coordinator — Sunamganj District', 'Youth Upskill Network (YUNet)', 'Jan 2026 – Present (6 mos)', 'Current', 'https://www.yunet.asia', 'teal', '/images/Youth Upskill Network.png', 'fas fa-users', '["Led campus-wide technical and leadership engagement initiatives for university students.","Organized workshops, outreach campaigns, and student programs focused on skill development.","Acted as liaison between students and the organization to improve participation and communication."]', '["Directed student workshops and upskilling webinars, acting as key campus liaison."]', 3),
(gen_random_uuid(), 'ilc', 'District Coordinator — Sunamganj District', 'International Leadership Competition', 'Nov 2025 – Present (8 mos)', 'Ongoing', 'https://ilc.ysditrust.com', 'rose', '/images/International Leadership Competition.jpeg', 'fas fa-globe', '["Coordinated district-level operations, student participation, and event execution across venues.","Managed volunteer teams and supported competition logistics, outreach, and resource planning."]', '["Supervised venue arrangements, logistics, and volunteer teams for leadership events."]', 4),
(gen_random_uuid(), 'it', 'Director of IT', 'Anto Huzrapur Jubo Shangho', '2024 – Present (2 yrs)', 'Ongoing', '#', 'blue', '/images/DJS.jpg', 'fas fa-briefcase', '["Managed organizational IT systems, digital platforms, and technical operations end-to-end.","Led technical teams supporting digital transformation and online content management initiatives.","Maintained workflow automation scripts to improve operational reliability and team productivity."]', '["Managed organizational IT networks, live digital broadcasts, and automation scripts."]', 5)
ON CONFLICT (key) DO UPDATE SET role = EXCLUDED.role;

INSERT INTO public.projects (id, key, title, category, status, image_url, fallback_icon, tech_stack, description, live_url, github_url, is_placeholder, bullets, sort_order) VALUES
(gen_random_uuid(), 'mangostar', 'Mango Star', 'E-Commerce Platform', 'Production Ready', '/images/Mango Star.png', '', '["React","TypeScript","Supabase","Tailwind CSS","TanStack Query","Node.js","Express.js","PostgreSQL","Stripe"]', 'A modern full-stack e-commerce platform built for seamless online shopping with secure authentication, real-time database integration, product management, shopping cart, order tracking, and responsive user experience.', 'https://mangostar.store', 'https://github.com/masudul2002', false, '["Developed a modern full-stack e-commerce platform featuring secure user authentication, shopping cart, and Stripe payment integration.","Built real-time database transactions and database querying using PostgreSQL and Supabase.","Optimized front-end data fetching and state caching using React, Tailwind CSS, and TanStack Query, enhancing mobile responsiveness."]', 0),
(gen_random_uuid(), 'djs', 'DJS Management System', 'Accounting & Member Management', 'Live', '/images/DJS.jpg', '', '["React","TypeScript","Supabase","Tailwind CSS","TanStack Query"]', 'End-to-end accounting and member management platform for Dhipidanga Jubo Shongha. Features RBAC, financial dashboards, live alerts, responsive sidebar navigation, and Bengali report generation.', 'https://djs-org.vercel.app', '', false, '["Designed and built an end-to-end accounting and member management platform featuring RBAC and financial dashboards.","Integrated Supabase real-time auth and database listeners for live alerts and seamless synchronization.","Implemented responsive sidebar navigation, Shadcn/UI components, and PDF report generation in Bengali."]', 1),
(gen_random_uuid(), 'mess', 'Mess Management System', 'Web Application Prototype', 'Prototype', '', 'fas fa-utensils', '["JavaScript","HTML","CSS"]', 'A web-based system designed to manage mess activities and finances.', '#', '', false, '["Built a web-based financial management system designed to track daily mess activities, meals, and expenditures.","Created modular JavaScript calculations for automated balance splitting and financial reporting.","Implemented localStorage persistence and lightweight CSS layouts for smooth performance."]', 2),
(gen_random_uuid(), 'comingsoon', 'Coming Soon', 'P3', 'In Dev', '', '', '[]', 'Details about an ongoing or planned project. Stay tuned for more amazing work.', '#', '', true, '[]', 3)
ON CONFLICT (key) DO UPDATE SET title = EXCLUDED.title;

INSERT INTO public.cv_targets (id, key, title, score, keywords, summary, skills, experience_bullets, project_bullets, activities, sort_order) VALUES
(gen_random_uuid(), 'se', 'Software Engineer', 92, '["C++","Python","JavaScript","OOP","Algorithms","Git","Full-Stack","REST API","Debugging"]', 'Computer Science and Engineering undergraduate with strong interest in software engineering, full-stack web development, and competitive programming. Proven leadership experience in organizing large-scale technical events and driving community engagement. ICPC 2025 participant with hands-on experience in building production-grade web applications. Seeking software engineering opportunities to leverage algorithmic skills and deliver scalable, maintainable technology solutions.', '[["Programming & CS Foundations","C++, Python, JavaScript, Data Structures, Algorithms, OOP, Problem Solving"],["Software Engineering","Full-Stack Development, System Design, Debugging, Code Review, REST APIs"],["Leadership & Communication","Event Management, Team Coordination, Community Building, Public Speaking"],["Tools & Platforms","Git/GitHub, Firebase, Linux, VS Code, Online Judges, Technical Documentation"]]', '{"it":["Managed organizational IT systems, digital platforms, and technical operations end-to-end.","Led technical teams supporting digital transformation and online content management initiatives.","Maintained workflow automation scripts to improve operational reliability and team productivity."],"ph":["Representing Programming Hero on campus, promoting coding education and structured learning paths.","Organizing peer learning sessions, coding bootcamp awareness, and student onboarding events."]}', '{"djs":["Designed and built an end-to-end accounting and member management platform featuring RBAC and financial dashboards.","Implemented Firebase security rules and real-time database ensuring data accountability and compliance."],"mess":["Built a web-based financial management tool with expense tracking, billing, and balance reports.","Applied modular JS architecture with localStorage persistence and clean responsive interface."]}', '[]', 0),
(gen_random_uuid(), 'ft', 'FinTech Developer', 95, '["Payment APIs","bKash","Security","Firebase","JavaScript","FinTech","REST APIs","Stripe","PostgreSQL"]', 'Computer Science and Engineering undergraduate with a strong focus on financial technology, secure payment systems, and web development. Built a production-ready payment portal integrating bKash QR-code payment, PDF receipt generation with unique transaction IDs, and a mandatory compliance workflow. Combines hands-on API integration experience with analytical problem-solving skills and leadership in technology-driven community initiatives. Eager to deliver secure, scalable FinTech solutions.', '[["FinTech & Payments","bKash API, Stripe API, QR Payment, Transaction Management, PDF Receipt Generation, Security"],["Programming & Engineering","JavaScript, C++, Python, REST APIs, Firebase, SQL, PostgreSQL, Data Validation"],["Leadership & Communication","Event Management, Team Coordination, Community Building, Public Speaking"],["Tools & Platforms","Git/GitHub, Firebase, VS Code, Linux, Technical Documentation"]]', '{"it":["Architected and deployed secure digital payment workflows and mobile financial transaction systems.","Integrated bKash financial API enabling QR-based and link-based mobile payment processing.","Built PDF receipt engine with unique transaction IDs, timestamps, and digital signature output."],"ph":["Promoted Programming Hero FinTech learning paths and secure coding fundamentals among campus peers.","Connected students with industry-relevant programming resources and mentorship opportunities."]}', '{"mangostar":["Developed a modern full-stack e-commerce platform featuring secure user authentication, shopping cart, and Stripe payment integration.","Built real-time database transactions and database querying using PostgreSQL and Supabase."],"djs":["Implemented secure financial accounting and transactional dashboards with real-time audit trails.","Designed audit trail and activity logging to support transparency and data governance."],"mess":["Developed real-time expense tracker with automated balance calculation and PDF invoice generation.","Applied input validation, data sanitization, and access-control patterns for financial data security."]}', '[]', 1),
(gen_random_uuid(), 'be', 'Backend Developer', 88, '["Python","SQL","Firebase","Linux","REST APIs","Git","C++","Node.js","Express.js","PostgreSQL"]', 'Computer Science and Engineering undergraduate with a strong focus on backend systems, database architecture, and server-side development. Proficient in Python, C++, SQL, and Firebase. Skilled in designing efficient data models, building REST API integrations, and administering Linux environments. Strong algorithmic foundation from competitive programming enables writing optimized, performant server-side code. Committed to building scalable, reliable backend systems through real-world project experience.', '[["Programming & CS Foundations","Python, C++, JavaScript, SQL, PostgreSQL, Data Structures, Algorithms, OOP"],["Backend & Database","Node.js, Express.js, Firebase, REST APIs, Database Design, Linux Administration, Server Scripting"],["Leadership & Communication","Event Management, Team Coordination, Community Building, Public Speaking"],["Tools & Platforms","Git/GitHub, Linux, VS Code, Firebase Console, Technical Documentation"]]', '{"it":["Designed and maintained backend data systems supporting multi-user digital operations and reporting.","Developed Python scripts with SQL queries to automate data aggregation and operational workflows.","Administered Linux environments ensuring system reliability, uptime, and data integrity."],"ph":["Advocating Programming Hero backend and systems programming curriculum among university students.","Facilitating peer code reviews and study groups focused on backend development practices."]}', '{"mangostar":["Developed robust backend REST APIs using Node.js and Express.js with PostgreSQL database schema.","Designed Firestore schema with normalized collections, efficient queries, and real-time listeners."],"djs":["Designed database models and backend listeners for real-time member updates using Supabase.","Implemented role-based access control and server-side validation for secure data management."],"mess":["Architected backend data model with validation, Firebase persistence, and structured error handling.","Built modular, server-side JavaScript calculations applying separation-of-concerns principles."]}', '[]', 2),
(gen_random_uuid(), 'cp', 'Competitive Programmer', 90, '["C++","Algorithms","Dynamic Programming","Graph Theory","Codeforces","ICPC","Python","Data Structures"]', 'Computer Science and Engineering undergraduate with expert proficiency in C++ and a deep command of advanced algorithms, dynamic programming, graph theory, and number theory. Active competitive programmer on Codeforces, consistently solving problem sets and targeting ICPC 2026 participation. Strong mathematical foundation supports exceptional computational and analytical skills. Applies rigorous problem-solving thinking to deliver efficient, optimized real-world software solutions.', '[["Programming & Algorithms","C++, Python, Dynamic Programming, Graph Theory, Binary Search, Greedy Algorithms"],["CS Foundations","Data Structures, Number Theory, Segment Trees, OOP, Problem Decomposition"],["Leadership & Communication","Event Management, Team Coordination, Mentoring, Community Building"],["Tools & Platforms","Codeforces, LeetCode, AtCoder, Git/GitHub, Linux, Online Judges"]]', '{"it":["Applied algorithmic optimization techniques to automate and accelerate organizational IT processes.","Developed Python scripts using hash-map and sorting algorithms, improving workflow efficiency by 60%.","Mentored team members on structured problem decomposition and systematic debugging methodology."],"ph":["Representing Programming Hero competitive programming track on campus — inspiring peers to compete.","Hosting informal algorithm study sessions and practice contests for fellow students."]}', '{"djs":["Designed an optimized search & filter algorithm for member lookup achieving O(log n) complexity.","Applied data structure best practices to handle real-time concurrent data operations efficiently."],"mess":["Applied map/sort data structures to build O(n log n) financial tracking and balance reconciliation.","Optimized runtime and memory usage for performance in browser-constrained environments."]}', '[]', 3),
(gen_random_uuid(), 'it', 'IT & Digital Marketing Specialist', 89, '["Digital Marketing","Social Media","Live Streaming","IT Management","Web Dev","SEO","Content Strategy"]', 'Computer Science and Engineering undergraduate with proven experience in IT management and digital marketing strategy. Currently serving as Director of IT — overseeing social media channels, live broadcast production, and content campaigns. Skilled web developer bridging marketing objectives with technical execution. Demonstrated leadership across campus, district, and organizational settings, consistently delivering measurable improvements in digital engagement. Seeking IT or digital marketing roles to drive meaningful organizational impact through technology.', '[["Digital Marketing","Social Media Management, Content Strategy, SEO, Campaign Planning, Analytics"],["IT & Development","Web Development, HTML5, CSS3, JavaScript, Firebase, IT Systems Management"],["Leadership & Communication","Event Management, Team Coordination, Live Streaming, Public Speaking"],["Tools & Platforms","Git/GitHub, Firebase, VS Code, Content Creation Tools, Meta Business Suite"]]', '{"it":["Directed full-scale digital strategy — managed social media presence, live streaming, and content publishing.","Produced and moderated live broadcast events, growing online audience engagement by 35%.","Executed targeted content campaigns that strengthened organizational brand visibility and community reach."],"ph":["Promoting Programming Hero digital skills and IT career tracks across campus channels and events.","Leveraging social media skills to amplify Programming Hero brand presence among students."]}', '{"djs":["Designed promotional materials and social media content to drive 40% increase in club enrollment.","Applied UX/UI and digital branding principles to deliver an intuitive, on-brand web experience."],"mess":["Managed full digital project lifecycle — requirements, design, development, deployment, and user feedback.","Created user documentation and promotional materials to drive system adoption among non-technical users."]}', '[]', 4)
ON CONFLICT (key) DO UPDATE SET title = EXCLUDED.title;

